[package]
name = "path"
version = "0.1.0"
authors = ["yukimemi <yukimemi@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
argopt = "0.1.1"
structopt = "0.3.18"
anyhow = "1.0.32"
